name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3

      - name: Simple Build
        run: python make.py

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: cibuildwheel
        run: python -m cibuildwheel --output-dir wheelhouse